### ISSUE TITLE
문장의 어조와 외국 고유 명사 형식 통합 문제

### ISSUE THREAD

**Issue by nErumin** [CAU-DOSC/TransSum09#1]
* 문장의 어조가 일치하지 않는다.
    - 친화적인 어조로 전개할 것인가? ex) 통합할 필요가 있습니다.
    - 절제 어조로 전개할 것인가? ex) 통합할 필요가 있다.
* 외국 고유 명사(사람 이름/기업 이름)를 표기하는 방법이 일치하지 않는다.
    - 순수 영어로 표시할 것인가? ex) Google, Amazon, eBay
    - 한글 발음으로 표시할 것인가? ex) 구글, 아마존, 이베이

의견을 제시해주세요!

**Comment by jm6534** [comment]
- 문장의 어조 : 제가 번역한 앞 부분 말고는 친화적인 어조를 띄고 있네요. 앞 부분의 어조를 친화적 어조로 바꾸는 게 좋아보입니다.
- 고유명사 : 전부 영어로 표기하는 것이 좋아보입니다. 발음이 애매한 부분들도 있으니까요.

**Comment by dispe1** [comment]
문장의 어조는 전체적인 흐름에 맞춰서 통일해 주면 될것 같습니다.
그리고 고유 명사는 누구나 알만한 것은 한글로 하고 이름이나 책은 영어로 번역했었는데,
통일되게 영어로 고치는게 좋을 것 같습니다.
그리고 commoditization을 범용화로 번역했었는데, 영어의 뜻을 실제로 살리기가 애매해서 이런 단어는 영어로 그냥 놔둘지도 생각해 보면 좋을 것 같습니다.

**Comment by jm6534** [comment]
영어의 뜻을 살리기 힘든 것이라고 하니까 제가 번역한 쪽의 상용화, 상품에 해당하는 Commodification, Commodity 또한 그렇습니다. 한글로 쓰고 괄호로 영어를 써주는 것도 좋을 것 같습니다.
ex) 상품(Commodity)

**Comment by nErumin** [comment]
그러면 일단 어조 문제는 친화적인 어조로 통일을 하고, 고유 명사 역시 영어로 표기하는 것으로 하겠습니다.

해석이 애매한 단어는 한글/영어 표기를 병행하는 것도 괜찮은 것 같네요.
Commodity / Commodification / Commoditization 외에 해석이 애매한 것이 있나요?

**Comment by nErumin** [comment]
일단 해결된 문제이므로 닫습니다.
