### ISSUE TITLE
내용/문단의 가독성 문제

### ISSUE THREAD

**Issue by nErumin** [CAU-DOSC/TransSum09#3]
- 문단의 구성이 알맞은가?
    - 들여쓰기 간격은 적절한가?
    - 문장 간 간격은 적절한가?
- 그 외, 고려할만한 사항이 있으면 코멘트로 남겨주세요.

**Comment by nErumin** [comment]
들여쓰기/문장 사이의 공간이 조금 협소한것 같아, 일단 이슈로 남겨봅니다.

**Comment by jm6534** [comment]
문단 시작의 들여쓰기는 너무 간격이 작은 느낌은 있지만, 문장 간 간격은 괜찮다고 생각합니다.

**Comment by dispe1** [comment]
한칸 정도 더 띄면 좋을거 같긴한데, 지금상태로도 보는데는 문제 없다고 생각합니다.

**Comment by nErumin** [comment]
음... 알겠습니다. 일단 문장 간 간격은 유지하고, 문단 들여쓰기를 조정하도록 하겠습니다.

&nbsp;문단의 시작
다음 문장

&nbsp;&nbsp;문단의 시작
다음 문장

&nbsp;&nbsp;&nbsp;문단의 시작
다음 문장

&nbsp;&nbsp;&nbsp;&nbsp;문단의 시작
다음 문장

위 넷 중 무엇이 제일 나은가요?
개인적으로 저는 4번이 나은 것 같습니다.

**Comment by jm6534** [comment]
저도 4번이 좋아보입니다.

**Comment by nErumin** [comment]
네. 그렇다면 4번 방향으로 수정하는 것으로 하겠습니다.

다른 의견이 있으시면 별도의 이슈로 등록해주세요.

이 이슈에 대해서는 해결이 된 것 같으니 닫습니다!
